# Generated by Django 4.2.15 on 2024-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
